service: promodeagro-ecom-packer-api

frameworkVersion: "3"

useDotenv: true

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  stage: ${self:custom.stage}
  region: us-east-1
  runtime: nodejs18.x
  role: arn:aws:iam::851725323791:role/ecommerce_Lambda_Role

functions:
  - ${file(home/function.yml)}
  # - ${file(notification/function.yml)}
  - ${file(profile-details/function.yml)}
  # - ${file(login/function.yml)}

  
plugins:
  - serverless-offline
