functions:  
  unpackedOrders:
    handler: src/handlers/orders.unpacked_orders
    events:
      - http:
          path: orders/unpacked
          method: get
  packedOrders:
    handler: src/handlers/orders.packed_orders
    events:
      - http:
          path: orders/packed
          method: get
  startOrder:
    handler: src/handlers/orders.start_order
    events:
      - http:
          path: orders/start/{order_id}
          method: get
  completeOrder:
    handler: src/handlers/orders.complete_order
    events:
      - http:
          path: orders/complete
          method: post 
  createOrder:
    handler: src/handlers/orders.create_order
    events:
      - http:
          path: orders
          method: post
  assignPacker:
    handler: src/handlers/orders.assign_packer
    events:
      - http:
          path: orders/{order_id}/assign-packer
          method: post
  markItemsUnavailable:
    handler: src/handlers/orders.mark_items_unavailable
    events:
      - http:
          path: orders/{order_id}/mark-items-unavailable
          method: post
  assignRider:
    handler: src/handlers/orders.assign_rider
    events:
      - http:
          path: orders/{order_id}/assign-rider
          method: post 